### ISSUE TITLE
Regarding runnimg simulation in ns3

### ISSUE THREAD

**Issue by madhavi06** [g4rr3t/aodv-blackhole-detection#1]
Its giving error as Normalapp.c is not given. and included in simulation.cc. Pklease give its code also

**Comment by g4rr3t** [comment]
I made no changes to simulation.cc or anything else beyond what is in this repo.  Download NS-3 version 3.21, build it, run the examples. Build and run NetAnim.  Follow the NS-3 documentation guides.  After you have it working, then paste my code into the directories and build and run the simulations.   I'm not going to provide the ns-3 code because it is freely available.

**Comment by MOLYshhh** [comment]
Does it work properly
